// Build script: scan content/*.md -> src/articles-data.js
// Run before vite build: node scripts/build-content.mjs
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { join, basename } from 'node:path';
import { marked } from 'marked';

const contentDir = join(process.cwd(), 'content');
const outFile = join(process.cwd(), 'src', 'articles-data.js');

function parseFrontmatter(text) {
  const lines = text.split(/\r?\n/);
  if (lines[0]?.trim() !== '---') return { meta: {}, body: text };
  let i = 1;
  const meta = {};
  for (; i < lines.length; i++) {
    const line = lines[i];
    if (line.trim() === '---') break;
    const idx = line.indexOf(':');
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    let value = line.slice(idx + 1).trim();
    // parse simple arrays: [a, b]
    if (value.startsWith('[') && value.endsWith(']')) {
      value = value.slice(1, -1).split(',').map((s) => s.trim().replace(/^["']|["']$/g, '')).filter(Boolean);
    } else {
      value = value.replace(/^["']|["']$/g, '');
    }
    meta[key] = value;
  }
  const body = lines.slice(i + 1).join('\n').trim();
  return { meta, body };
}

function slugify(name, title) {
  const slug = basename(name, '.md').trim();
  return slug || String(title || 'article').replace(/\s+/g, '-');
}

const files = readdirSync(contentDir)
  .filter((f) => f.endsWith('.md'))
  .sort((a, b) => statSync(join(contentDir, b)).mtimeMs - statSync(join(contentDir, a)).mtimeMs);

const articles = files.map((file) => {
  const raw = readFileSync(join(contentDir, file), 'utf8');
  const { meta, body } = parseFrontmatter(raw);
  const title = meta.title || basename(file, '.md');
  const html = marked.parse(body, { gfm: true, breaks: true });
  return {
    slug: slugify(file, title),
    title,
    date: meta.date || '',
    category: meta.category || '未分类',
    tags: Array.isArray(meta.tags) ? meta.tags : [],
    source: meta.source || '',
    source_url: meta.source_url || '',
    summary: meta.summary || html.replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').slice(0, 120),
    html,
  };
});

const payload = `// AUTO-GENERATED by scripts/build-content.mjs — do not edit by hand
export const articles = ${JSON.stringify(articles, null, 2)};
`;
writeFileSync(outFile, payload, 'utf8');
console.log(`[build-content] ${articles.length} articles -> ${outFile}`);